### PR TITLE
Modernize code with ES6: Add linter

### PR DESCRIPTION
**Pull request by afrokick**
- [x] add instruction how to run tests + `npm run test`
- [x] add ESLint + `npm run lint`
- [x] add `.prettierrc` cause it is better then WebStorm style guides)
- [x] add `@types/meteor`
- [x] modernize some files for example

I'm also willing to add TS, but the target version of Meteor doesn't allow it.

### CODE REVIEW

**Comment by afrokick** [comment]
@zodern ready for review

**Comment by afrokick** [comment]
@zodern @harryadel Should I do some changes to PR to prepare it for merging?

**Comment by zodern** [comment]
Thanks @afrokick. For some reason GitHub actions isn't running the tests. I think if you merge the master branch into your branch, it should fix the tests not running.

**Comment by afrokick** [comment]
@zodern done! The action is in the pending state, so, someone should approve pr to unblock tests

**Comment by afrokick** [comment]
Revert nullish coalescing operator, because it doesn't work on meteor < 1.8.2

**Comment by harryadel** [comment]
Thanks for your contribution and time. I'm only able to run the workflow but @zodern is the one responsible for reviewing and merging.

**Comment by afrokick** [comment]
@harryadel thank you for your help. Now all tests passed!

**Comment by zodern** [comment]
Thanks @afrokick. Sorry for the delay in merging.

**Pull request merged**
