### PR TITLE
Redis-oplog compatibility

### LINKED ISSUE #43: Live queries empty with redis-oplog
I have had this issue since I started using Monti. Nothing in the Live queries tab, which would have been extremely useful.

We are using cultofcoders:redis-oplog@2.0.5
Screenshot_20211011_174033

### PR DESCRIPTION
**Pull request by fumbleforce**
Should resolve #43

### CODE REVIEW

**Comment by jorgeer** [comment]
Any thoughts on this? I think it would be mighty handy for anyone using redis-oplog.

**Comment by jorgeer** [comment]
No idea why this test would fail, the redis-oplog hijacking shouldn't happen during this test.

**Review by zodern — COMMENTED** [review]
This looks good. I'm not very familiar with redis oplog, so I have some questions:

- This doesn't seem to track synthetic events. Would this be useful to add in the future?
- When a query has a limit or skip, sometimes `addById` will be called instead of `add` on the observableCollection.
- If I am understanding the code for redis oplog correctly, unless `protectAgainstRaceConditions` is true it will fetch the doc from the database every time it is updated. It seems the `protectAgainstRaceConditions` option should be checked to know if polledDocuments should be incremented for updates and maybe inserts.

Some things we might want to look into tracking in the future:
- When the query has a limit or skip, it seems after many changes redis oplog will run the query again to get the list of ids: https://github.com/cult-of-coders/redis-oplog/blob/b2be29ddc2feee460d248a7e5daffd2883c4e512/lib/processors/actions/requery.js#L16-L17.

**Comment by jorgeer** [comment]
Very good observations, I will look further into this. When trying out the fork in my beta environment, I am also seeing strange things with the added/changed/removed redis messages, almost as if they are using the payload `size` property instead of the count, resulting in massive numbers. So more research is needed.

**Comment by zodern** [comment]
Hi @jorgeer. Have you had a chance to look into this? If you've lost interest, I can finish it for you.

**Comment by jorgeer** [comment]
Hey, thanks for following up @zodern. I did fiddle with it a little, but I've been swamped with work since then, so I can't afford to work on it currently. If you have the time, I would not mind of course if you finished it, the feature is still very valuable.

**Comment by alisnic** [comment]
@zodern is there a way I can help to push this forward? I can do some testing

**Comment by leonardoventurini** [comment]
I started working on this, I created a separate internal branch for this, once I push the initial set of changes I will link it here.

**Comment by leonardoventurini** [comment]
Hi, this is the PR I am working on #103

I am adding tests, can you suggest some test cases to add? cc @zodern @fumbleforce @alisnic 

https://github.com/monti-apm/monti-apm-agent/pull/103/files#diff-ced7ed2f37fd05cf8fe5a8fbddcfc35f44a5e59c22537690bccea03534929d5d

**Pull request merged**
